BEGIN;

-- Update employee avatars with distinctive role-aligned emojis for all 51 staff members
UPDATE employees SET avatar = '📱' WHERE employee_id = 'alex';
UPDATE employees SET avatar = '💼' WHERE employee_id = 'ariana';
UPDATE employees SET avatar = '💻' WHERE employee_id = 'arun';
UPDATE employees SET avatar = '🧪' WHERE employee_id = 'ben';
UPDATE employees SET avatar = '📣' WHERE employee_id = 'blake';
UPDATE employees SET avatar = '⚙️' WHERE employee_id = 'chris';
UPDATE employees SET avatar = '🖌️' WHERE employee_id = 'cooper';
UPDATE employees SET avatar = '🤝' WHERE employee_id = 'dave';
UPDATE employees SET avatar = '✨' WHERE employee_id = 'desmond';
UPDATE employees SET avatar = '📊' WHERE employee_id = 'elena';
UPDATE employees SET avatar = '🍏' WHERE employee_id = 'ethan';
UPDATE employees SET avatar = '🔍' WHERE employee_id = 'felix';
UPDATE employees SET avatar = '📈' WHERE employee_id = 'hanna';
UPDATE employees SET avatar = '🎯' WHERE employee_id = 'isabel';
UPDATE employees SET avatar = '📐' WHERE employee_id = 'jamie';
UPDATE employees SET avatar = '👥' WHERE employee_id = 'janice';
UPDATE employees SET avatar = '🚀' WHERE employee_id = 'jenna';
UPDATE employees SET avatar = '🤖' WHERE employee_id = 'jordan';
UPDATE employees SET avatar = '💾' WHERE employee_id = 'kaitlyn';
UPDATE employees SET avatar = '🗂️' WHERE employee_id = 'karen';
UPDATE employees SET avatar = '🏗️' WHERE employee_id = 'lena';
UPDATE employees SET avatar = '🔧' WHERE employee_id = 'liam';
UPDATE employees SET avatar = '🎭' WHERE employee_id = 'marc';
UPDATE employees SET avatar = '🧭' WHERE employee_id = 'mike';
UPDATE employees SET avatar = '📲' WHERE employee_id = 'miki';
UPDATE employees SET avatar = '🔌' WHERE employee_id = 'mona';
UPDATE employees SET avatar = '🗄️' WHERE employee_id = 'morgan';
UPDATE employees SET avatar = '🎧' WHERE employee_id = 'nadia';
UPDATE employees SET avatar = '🏷️' WHERE employee_id = 'nisha';
UPDATE employees SET avatar = '📦' WHERE employee_id = 'nora';
UPDATE employees SET avatar = '🌟' WHERE employee_id = 'patty';
UPDATE employees SET avatar = '📡' WHERE employee_id = 'raj';
UPDATE employees SET avatar = '💻' WHERE employee_id = 'ravi';
UPDATE employees SET avatar = '🎁' WHERE employee_id = 'reese';
UPDATE employees SET avatar = '🍎' WHERE employee_id = 'sam';
UPDATE employees SET avatar = '🌐' WHERE employee_id = 'sanjay';
UPDATE employees SET avatar = '👑' WHERE employee_id = 'sarah';
UPDATE employees SET avatar = '🧩' WHERE employee_id = 'sophie';
UPDATE employees SET avatar = '🧱' WHERE employee_id = 'tasha';
UPDATE employees SET avatar = '🔬' WHERE employee_id = 'taylor';
UPDATE employees SET avatar = '🏢' WHERE employee_id = 'tom';
UPDATE employees SET avatar = '🩺' WHERE employee_id = 'umji';
UPDATE employees SET avatar = '🎬' WHERE employee_id = 'vince';
UPDATE employees SET avatar = '💬' WHERE employee_id = 'yara';
UPDATE employees SET avatar = '🎖️' WHERE employee_id = 'yusuf';
UPDATE employees SET avatar = '💡' WHERE employee_id = 'zoe';

COMMIT;
