/**
 * Scores the hiring-proposal rules (src/hiring-proposals.ts) against what the
 * simulated company actually did: OrgForge's own record of departures, hires
 * and hand-overs, exported offline by eval/orgforge/gap_truth.py.
 *
 *   DATABASE_URL=... node --import tsx scripts/backtest-hiring.ts
 *   # writes docs/evaluation/hiring-backtest.md
 *
 * The rules never see that record; this script is the only place the two meet.
 */
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { PostgresCompanyKnowledge } from "../src/adapters/postgres-company-knowledge.js";
import type { AsOf } from "../src/as-of.js";
import {
  ORPHAN_MIN_DAYS,
  OVERLOAD_MIN_DOMAINS,
  OVERLOAD_MIN_INCIDENTS,
  THIN_FRACTION,
  proposalsThrough,
  type HiringProposal,
} from "../src/hiring-proposals.js";

interface Truth {
  departures: Array<{ person: string; day: string; domains: string[]; before_record: boolean }>;
  hires: Array<{ person: string; day: string; role: string; domains: string[]; expertise: string[] }>;
  handovers: Array<{ domain: string; day: string; new_owner: string }>;
}

const root = new URL("../", import.meta.url);
const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) throw new Error("DATABASE_URL is required.");

const truth = JSON.parse(await readFile(new URL("eval/orgforge/gap-truth.json", root), "utf8")) as Truth;
const knowledge = new PostgresCompanyKnowledge(databaseUrl);
try {
  const days = await knowledge.workingDays();
  const first = days[0]!;
  const last = days.at(-1)!;
  const proposals = await proposalsThrough(days, (day) => knowledge.domainHealth(day as AsOf));
  const between = (from: string, to: string) =>
    Math.round((Date.parse(`${to}T00:00:00Z`) - Date.parse(`${from}T00:00:00Z`)) / 86_400_000);

  // Each hire inside the record: was a proposal for one of its domains open before it?
  const hires = truth.hires.filter((hire) => hire.day >= first).map((hire) => {
    const earlier = proposals
      .filter((p) => hire.domains.includes(p.domain) && p.openedOn <= hire.day)
      .sort((a, b) => a.openedOn.localeCompare(b.openedOn));
    return { hire, earlier, lead: earlier[0] ? between(earlier[0].openedOn, hire.day) : null };
  });

  // Each proposal: what followed — a hire for that domain, a hand-over, or nothing in the record.
  const outcome = (p: HiringProposal) => {
    const until = p.closedOn ?? last;
    const hire = truth.hires.find((h) => h.domains.includes(p.domain) && h.day >= p.openedOn && between(until, h.day) <= 14);
    if (hire) return `hire: ${hire.person} on ${hire.day} (+${between(p.openedOn, hire.day)} d)`;
    const handover = truth.handovers.find((h) => h.domain === p.domain && h.day >= p.openedOn && h.day <= until);
    if (handover) return `taken on internally: ${handover.new_owner} on ${handover.day}`;
    return "no hire or hand-over for it in the record";
  };

  const lines = [
    "# Hiring proposals: backtest",
    "",
    `Generated by \`scripts/backtest-hiring.ts\` over the ${days.length} working days ${first} to ${last}. The rules (\`src/hiring-proposals.ts\`) read only domain health (\`src/domain-health.ts\`). They are scored here against OrgForge's own record of departures, hires and hand-overs (\`eval/orgforge/gap-truth.json\`), which they never see.`,
    "",
    "## Rules and thresholds",
    "",
    `- **orphaned**: the owner has left and nobody has taken the domain on, for ${ORPHAN_MIN_DAYS}+ working days running. With 1 day, legacy auth service, mobile analytics and Project Titan are proposed on 2026-01-01 only because their hand-overs are recorded on the 2nd.`,
    `- **thin**: over a full 30-day window, at most ${THIN_FRACTION * 100}% of the median domain's contributors. The split in this corpus is wide: on 2026-01-30 kubernetes-deploy and terraform-infra have 5 each, the next domain 16, and the median 21. Before a full window, everything looks thin (on 2026-01-01 eight domains have ≤ 2).`,
    `- **overloaded**: the owner holds ${OVERLOAD_MIN_DOMAINS}+ domains and this one had ${OVERLOAD_MIN_INCIDENTS}+ incidents in 30 days. With 1 incident it fires on TitanDB from 2026-01-19, when Janice took on three domains and ENG-137 arrived. With 2, it fires from 2026-01-29.`,
    "",
    "## Summary",
    "",
    `- ${hires.filter((h) => h.lead !== null).length} of the ${hires.length} hires inside the record were preceded by a proposal for a domain they brought, by ${hires.filter((h) => h.lead !== null).map((h) => h.lead).join(", ")} days.`,
    `- ${proposals.length} proposals in ${days.length} working days. ${proposals.filter((p) => outcome(p).startsWith("hire")).length} were followed by a hire, ${proposals.filter((p) => outcome(p).startsWith("taken")).length} by someone inside taking the domain on, and ${proposals.filter((p) => outcome(p).startsWith("no hire")).length} by neither.`,
    "- Caveats: three hires is a very small sample. The thin threshold was chosen after looking at this same corpus, so this is not an out-of-sample result. The record has no hires after 2026-02-05, so later proposals cannot be confirmed either way. Reese and Ethan Patel were hired before Morgan left (a planned layoff), so the departure rule alone could not have preceded them; the thin rule did.",
    "",
    "## Did a proposal come before each hire?",
    "",
    "| Hire | Day | Role | Domains (from stated expertise) | Proposal before it | Lead |",
    "|---|---|---|---|---|---|",
    ...hires.map(({ hire, earlier, lead }) =>
      `| ${hire.person} | ${hire.day} | ${hire.role} | ${hire.domains.join(", ") || "—"} | ${earlier.map((p) => `${p.domain} (${p.rulesSeen.join("+")}, from ${p.openedOn})`).join("; ") || "none"} | ${lead === null ? "—" : `${lead} days`} |`),
    "",
    "## Every proposal, and what followed",
    "",
    "| Domain | Open | Closed | Rules that held | What followed |",
    "|---|---|---|---|---|",
    ...proposals.map((p) =>
      `| ${p.domain} | ${p.openedOn} | ${p.closedOn ?? "still open"} | ${p.rulesSeen.join(", ")} | ${outcome(p)} |`),
    "",
    "## Departures",
    "",
    "| Who | Left | Domains | A proposal open for it? |",
    "|---|---|---|---|",
    ...truth.departures.map((d) =>
      `| ${d.person} | ${d.day}${d.before_record ? " (before the record)" : ""} | ${d.domains.join(", ")} | ${d.domains.map((domain) => {
        // A proposal open on the day they left, or one opened after because the domain was orphaned.
        const from = d.before_record ? first : d.day;
        const p = proposals.find((q) => q.domain === domain && (
          (q.openedOn <= from && (q.closedOn === null || q.closedOn > from))
          || (q.rulesSeen.includes("orphaned") && q.openedOn >= from)));
        const owner = truth.handovers.find((h) => h.domain === domain);
        return `${domain}: ${p ? `yes, open ${p.openedOn}–${p.closedOn ?? "end"} (${p.rulesSeen.join(", ")})` : `no${owner ? ` (${owner.new_owner} took it on ${owner.day})` : ""}`}`;
      }).join("; ")} |`),
    "",
  ];
  const report = new URL("docs/evaluation/hiring-backtest.md", root);
  await writeFile(report, `${lines.join("\n")}\n`, "utf8");
  console.log(`${proposals.length} proposals; wrote ${fileURLToPath(report)}`);
} finally {
  await knowledge.close();
}
